### ISSUE TITLE
"Illegal operation" when importing wordbatch.extractors

### ISSUE THREAD

**Issue by michaldul** [anttttti/Wordbatch#17]
I can "import wordbatch", but importing wordbatch.extractors kills the interpreter with "Illegal opration".

My environment:
- CentOS Linux release 7.4.1708
- Python 3.6.3
- numpy 1.14.2
- cython 0.28.2
- scipy 1.0.1
- pandas 0.22.0

The environment I'm working with is not Anaconda, however, I was able to reproduce it on the very same OS with Python 3.6.4 on Anaconda.

**Comment by anttttti** [comment]
Thanks for the details. With Ubuntu 16.04 and Python 3.6 this doesn't reproduce. Since extractors.pyx compiles using Cython, I suspect the issue is with Cython or GCC compiler.

Also, currently the package compilation and dependencies are not done in the best possible way. Someone with Python+Cython package setup experience could have a look at setup.py and the __init__.py files, for related problems.
